#include "dllemvbase.h"

static int gEMVBaseTagBaseLibnum = 0;

static const EMVBASETAGITEM gEMVBaseTagBaseLib[]=
{

    {EMVTAG_IndustryIDNo,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,3,EMVTAGFORMAT_B,EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
    {EMVTAG_CardAID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,16,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_AppLabel,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,16,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
	{EMVTAG_PayPassTrack1Data,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,76,EMVTAGFORMAT_ANS,EMVTAGTYPE_PAYPASS|EMVTAGTYPE_DPAS},
    {EMVTAG_Track2Equ,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,19,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_PAN,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,10,EMVTAGFORMAT_CN,EMVTAGTYPE_ALL},
	{EMVTAG_CardHoldName,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_ANS,(EMVTAGTYPE_ALL&(~EMVTAGTYPE_PAYPASS)&(~EMVTAGTYPE_JSPEEDY))&(~EMVTAGTYPE_NSICCS)},
	{EMVTAG_CardHoldName,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,26,EMVTAGFORMAT_ANS,EMVTAGTYPE_JSPEEDY|EMVTAGTYPE_NSICCS},
	{EMVTAG_AppExpireDate,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,3,3,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_AppEffectDate,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,3,3,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_IssuCountryCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_TransCurcyCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_LangPrefer,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,8,EMVTAGFORMAT_AN,EMVTAGTYPE_ALL},
	{EMVTAG_ServiceCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_PANSeq,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_TransCurcyExp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_IssuerURL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
    {EMVTAG_IBAN,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,34,EMVTAGFORMAT_ANS,EMVTAGTYPE_PAYPASS},//20160529_lhd
	{EMVTAG_PAYPASS_AccountType,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},//20200702_LHD
    {EMVTAG_FCITemplate,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_SCRIPT1,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_SCRIPT2,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_RMTF2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_RMTF1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_AmtAuthBin,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_AIP,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_DFName,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,16,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_PUREMSUES,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_AppPriority,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_AuthorCode,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
	{EMVTAG_AuthRespCode,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_AN,EMVTAGTYPE_ALL},
	{EMVTAG_CDOL1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_CDOL2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_CVMList,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,(EMVTAGTYPE_ALL & (~EMVTAGTYPE_PAYPASS))},
	{EMVTAG_CVMList,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,10,250,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},//20191101_LHD
    {EMVTAG_CAPKI,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_IPKCert,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,248,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_IssuerAuthenData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,8,16,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_IPKRem,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_SignStatAppData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,248,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_AFL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,(EMVTAGTYPE_ALL & (~EMVTAGTYPE_PAYPASS))},
	{EMVTAG_AFL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,4,248,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TVR,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_TDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
	{EMVTAG_TCHashValue,EMVTAGUPDATECONDITION_K,20,20,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
    {EMVTAG_PIN,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_TransDate,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,3,3,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_TSI,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_TransTypeValue,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_DDFName,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,16,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_AcquireID,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_AmtAuthNum,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_AmtOtherNum,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_AmtOtherBin,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_AppDiscretData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT,0,32,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_TermAID,EMVTAGUPDATECONDITION_K,5,16,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_AUC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_AppVer,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_AppVerNum,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_ASRPD,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_AN,(EMVTAGTYPE_ALL & (~EMVTAGTYPE_PAYPASS))},
    {EMVTAG_CardHoldNameExt,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_ANS,(EMVTAGTYPE_ALL & (~EMVTAGTYPE_PAYPASS))},
    {EMVTAG_CardHoldNameExt,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,27,45,EMVTAGFORMAT_ANS,EMVTAGTYPE_PAYPASS},
	{EMVTAG_IACDefault,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_IACDenial,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_IACOnline,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_IssuAppData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,32,EMVTAGFORMAT_B,(EMVTAGTYPE_ALL & (~EMVTAGTYPE_PURE) & (~EMVTAGTYPE_NSICCS))},
	{EMVTAG_IssuAppData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,34,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},		//pure up to 34
	{EMVTAG_IssuAppData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,12,32,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},		//pure up to 34
    {EMVTAG_ICTI,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_AppPreferName,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,16,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
    {EMVTAG_LOATC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_LCOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_MerchCateCode,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_MerchID,EMVTAGUPDATECONDITION_K,15,15,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
    {EMVTAG_PINTryCount,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
    {EMVTAG_MIRPANLast4Digits, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_N, EMVTAGTYPE_MIR},
    {EMVTAG_TOKENREQUESTID, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_N, EMVTAGTYPE_EMV | EMVTAGTYPE_QPBOC | EMVTAGTYPE_JSPEEDY|EMVTAGTYPE_NSICCS},
	{EMVTAG_TOKENREQUESTID, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_N, EMVTAGTYPE_EXPRESSPAY | EMVTAGTYPE_PAYWAVE},//modify var len//sjz2020.9.7 // add Bahrain Visa 20210709
	{EMVTAG_CountryCode,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_FloorLimit,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_TermID,EMVTAGUPDATECONDITION_K,8,8,EMVTAGFORMAT_AN,EMVTAGTYPE_ALL},
    {EMVTAG_TRMData,EMVTAGUPDATECONDITION_K,1,8,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_IFD_SN,EMVTAGUPDATECONDITION_K,8,8,EMVTAGFORMAT_AN,EMVTAGTYPE_ALL},
    {EMVTAG_Track1Discret,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,128,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
    {EMVTAG_Track2Discret,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,128,EMVTAGFORMAT_CN,EMVTAGTYPE_ALL},
    {EMVTAG_TransTime,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,3,3,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_TermCAPKI,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_UCOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS|EMVTAGTYPE_PURE},
    {EMVTAG_PayAccountRefer,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,29,29,EMVTAGFORMAT_AN,(EMVTAGTYPE_ALL & (~EMVTAGTYPE_RUPAY))},
    {EMVTAG_PayAccountRefer,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_AN,EMVTAGTYPE_RUPAY | EMVTAGTYPE_PAYWAVE}, // add Bahrain Visa 20210709
    {EMVTAG_PANLast4Digits, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_N, EMVTAGTYPE_EMV | EMVTAGTYPE_QPBOC | EMVTAGTYPE_JSPEEDY | EMVTAGTYPE_EXPRESSPAY | EMVTAGTYPE_MIR},
	{EMVTAG_PANLast4Digits,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_AN,EMVTAGTYPE_PAYWAVE}, // add Bahrain Visa 20210709
	{EMVTAG_AppCrypt,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,8,8,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_CryptInfo,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_ExpressPayKernelID,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_ICCPIN_EPKCert,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,248,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
    {EMVTAG_ICCPIN_EPKExp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,3,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
    {EMVTAG_ICCPIN_EPKRem,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,42,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
	{EMVTAG_IPKExp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,3,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_TermCapab,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_CVMResult,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_TermType,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_ATC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_UnpredictNum,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_PDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_POSEntryMode,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_AmtReferCurcy,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_AppReferCurcy,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,8,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_TransReferCurcyCode,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_TransReferCurcyExp,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_TermAddCapab,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_TransSeqCount,EMVTAGUPDATECONDITION_K,2,4,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_AppCurcyCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_AppReferCurcyExp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,4,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
	{EMVTAG_AppCurcyExp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_ALL},
    {EMVTAG_DataAuthCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_ICCPKCert,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,248,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_ICCPKExp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,3,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_ICCPKRem,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_DDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_SDATagList,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_SignDynAppData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,248,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_ICCDynNum,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,8,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_LogEntry,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_MerchantName,EMVTAGUPDATECONDITION_K,0,80,EMVTAGFORMAT_ANS,EMVTAGTYPE_ALL},
	{EMVTAG_AppDualCurcyCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_OfflineAccumulatorBalance,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS|EMVTAGTYPE_PURE},
    {EMVTAG_JCBCardholderVerifyStatus,EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_DRDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_JCBTermcmpIndicator,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
	{EMVTAG_JCBTermcmpIndicator,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_AN,EMVTAGTYPE_PAYWAVE}, // add Bahrain Visa 20210709
	{EMVTAG_MCHIPTransCateCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_AN,EMVTAGTYPE_PAYPASS},
	{EMVTAG_JCBDynamicTIP,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_DSODSCard,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,0,160,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_MembProductID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,8,EMVTAGFORMAT_AN,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_PaywaveAppProgId,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,16,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_ProductMembNum,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,32,EMVTAGFORMAT_AN,EMVTAGTYPE_EXPRESSPAY},
	{EMVTAG_DSDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,0,250,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_IssuerScriptREsult,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
    {EMVTAG_DSOperatorID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,8,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_JCBMSDObjectList,EMVTAGUPDATECONDITION_RA,0,252,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_qPBOCOfflineSpendAmount,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYWAVE|EMVTAGTYPE_QPBOC},
    {EMVTAG_AppCapabilitiesInfor,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DSID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,8,11,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DSSlotAvail,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_JCBOfflineBalance,EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_JSPEEDY},
	{EMVTAG_PaypassCVC3Track1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_JCBIssuerUpdateParameter,EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
	{EMVTAG_PaypassCVC3Track2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_CardHoldIdNo,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,40,EMVTAGFORMAT_ANS,EMVTAGTYPE_EMV},
	{EMVTAG_NSICCSAppControl,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
	{EMVTAG_PaypassPCVC3Track1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_CardHoldIdType,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_EMV},
	{EMVTAG_NSICCSGeographicControl,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_PaypassPunatcTrack1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_CardIdentifyInfo,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,16,EMVTAGFORMAT_B,EMVTAGTYPE_EMV | EMVTAGTYPE_QPBOC | EMVTAGTYPE_PAYWAVE},
	{EMVTAG_NSICCSPinEncControl,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
	{EMVTAG_Paypassnatctrack1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_NSICCSIssuerScriptLimit,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_PaypassPcvc3Track2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_NSICCSIssuerACProprietaryData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,20,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_TermTransPredicable,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE|EMVTAGTYPE_QPBOC|EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
	{EMVTAG_PaypassPunatcTrack2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_NSICCSIssuerCountryCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_PaypassNatcTrack2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_FromFactor,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_N,EMVTAGTYPE_EXPRESSPAY},//APPLUS request don't check maxlen
	{EMVTAG_NSICCSPinTryLimit,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
	{EMVTAG_NSICCSDerivationKeyIndex,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
	{EMVTAG_CardAuthData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE|EMVTAGTYPE_QPBOC},
	{EMVTAG_PayPassUDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_NSICCSIssuerProprietaryInternalData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,250,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_paypassun,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
	{EMVTAG_NSICCSIssuerProprietaryRecordData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,250,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_PaypassMagTrack2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,19,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_NSICCSTerminalProprietaryData,EMVTAGUPDATECONDITION_K,48,48,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_CardTransPredicable,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE|EMVTAGTYPE_QPBOC|EMVTAGTYPE_DPAS},
	{EMVTAG_NSICCSIssuerBankID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
	{EMVTAG_paypassMagAppVer,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_ECResetThreshold,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_EMV},
	{EMVTAG_NSICCSBeneficiaryBankID,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
	{EMVTAG_ClessReaderCapab,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_EXPRESSPAY},
	{EMVTAG_EnhancedClessReaderCapab,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_FormFactIndicator,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PaypassThirdPartyData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,32,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_CLPaymentDeviceType,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_MB},
	{EMVTAG_JCBDeviceInfo,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_DSSlotManage,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_ProtectedDataEnvelope1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PUREGDDOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_MIRCDAResult, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_CardInfAndPayCapab,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_ProtectedDataEnvelope2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_MIRCardProcessRequirement, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_DPASCPR, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
	{EMVTAG_MobileCVMResult,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_ProtectedDataEnvelope3,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PUREMSID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,16,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_ProtectedDataEnvelope4,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PURESCRIPTResult,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,10,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_ProtectedDataEnvelope5,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_VLPIssuAuthorCode,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_AN,EMVTAGTYPE_EMV},
    {EMVTAG_PUREDEUResult,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_UnprotectedDataEnvelope1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_PUREECHO,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,20,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_UnprotectedDataEnvelope2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_PURETransData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_UnprotectedDataEnvelope3,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_MaxECCashBalance,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_EMV},
	{EMVTAG_PUREDedicatedData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_AppSpecVersion,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_EXPRESSPAY},//APPLUS request don't check maxlen
	{EMVTAG_BancomatFormFactorIndicator,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
	{EMVTAG_UnprotectedDataEnvelope4,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_UnprotectedDataEnvelope5,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,192,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_VLPAvailableFund,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_EMV},
    {EMVTAG_BancomatIACSwitchInterface,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
    {EMVTAG_VLPIndicator,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_EMV},
	{EMVTAG_VLPTransLimit,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_EMV},
	{EMVTAG_MCLSecureCardFrame,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,64,64,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_CustomerExclusiveData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_CustomerExclusiveData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,33,EMVTAGFORMAT_B,EMVTAGTYPE_QPBOC},
	{EMVTAG_paypassMerchantCustomData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,20,20,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_JCBPartnerDiscretionaryData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,32,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_DSSummary1,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,8,16,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DPASVERNO, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
	{EMVTAG_NSICCSCardLifeCycleData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,36,36,EMVTAGFORMAT_B,EMVTAGTYPE_NSICCS},
    {EMVTAG_MobileSupportIndicator,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DPASDCVVV2, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 3, 3, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
    {EMVTAG_DSUnpredictableNumber,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DPASDCVVV1, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 3, 3, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
    {EMVTAG_FCIProterty,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_FCIDisData,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_MIRSignedApplicationTags, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRUnsignApplicationTags, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_PUREMSReadTemp,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_PURECCID,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_PURETTPI,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_PURECRMCD,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_DPASOfflineBalance, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
	{EMVTAG_WalletProviderNo, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
	{EMVTAG_PAYWAVEAP_RCTL,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PAYWAVEAP_CVMLimit,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PUREDF01,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_PAYWAVEAP_FloorLimit,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PUREDF02,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_PAYWAVEAP_EDDAVersion,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PUREDF03,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_RupayServiceAvailabilityInfo, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_PAYWAVEAP_CVMREQ,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PUREDF04,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_PAYWAVEAP_DispOfflineFundInd,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
	{EMVTAG_PUREDF05,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_PaywaveRCP,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYWAVE},
    {EMVTAG_PUREDF06,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_PUREDF07,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_RupayServiceDirectory, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_PUREDF08,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_PUREDF09,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_PUREDF0A,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
    {EMVTAG_LOATC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
	{EMVTAG_PURECOTC, EMVTAGUPDATECONDITION_K, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_PURE},
	{EMVTAG_RupayServiceManageInfo, EMVTAGUPDATECONDITION_K, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayServiceID, EMVTAGUPDATECONDITION_K, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_PURELCOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_PUREUCOL,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_RupayServiceSummary, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 8, 16, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayServiceSignature, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 8, 16, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayServiceRelatedData, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayCardCVMLimit, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayTermAddCapabExtern, EMVTAGUPDATECONDITION_K, 5, 5, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_DPASCardFeatureVersionNum, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
    {EMVTAG_DPASCardFeatureVersionNum, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 1, 2, EMVTAGFORMAT_B, EMVTAGTYPE_EMV},
    {EMVTAG_RupayAUCExtern, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_DPASCardFeatureDescriptor, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS|EMVTAGTYPE_EMV},
    {EMVTAG_DPASExtendedLoggingData, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 1, 32, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
	{EMVTAG_CardID, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 11, 64, EMVTAGFORMAT_B, EMVTAGTYPE_DPAS},
	{EMVTAG_CardID, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 1, 64, EMVTAGFORMAT_B, EMVTAGTYPE_EMV},
    {EMVTAG_MIRTransRecoveryCounter, EMVTAGUPDATECONDITION_K, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
    {EMVTAG_PUREAppVerUL, EMVTAGUPDATECONDITION_K, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_PURE},
    {EMVTAG_PUREAppVerLL, EMVTAGUPDATECONDITION_K, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_PURE},
	{EMVTAG_RupayServiceTermData, EMVTAGUPDATECONDITION_K, 0, 96, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayPRMicc, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 2, 8, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_POSCII,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_RupayPrePRMicc, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 8, 8, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_POSCII,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_AN,EMVTAGTYPE_PAYWAVE}, // add Bahrain Visa 20210709
    {EMVTAG_RupayCardTransLimit, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_CirqueLogEntry,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_EMV},
	{EMVTAG_RupayPRMacqKeyIndexCard, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_MIRTerminalFloorLimit, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRTerminalNoCVMLimit, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRTermCLLimit_NonCDCVM, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRTermclLimit_CDCVM, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 6, 6, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_RupayPRMacqKCV, EMVTAGUPDATECONDITION_K, 3, 3, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
	{EMVTAG_MIRTerminalTPMCapabilities, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRTransRecoveryLimit, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_DSInputCARD,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,8,8,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DSDigestH,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,8,8,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_QCARDPLUS,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_QPBOC},
	{EMVTAG_RupayICCDynamicSignatureRecordID, EMVTAGUPDATECONDITION_K| EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_RUPAY},
    {EMVTAG_DSODSInfo,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DSODSTerm,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,160,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_ODAalgrthFlag,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_QPBOC},
    {EMVTAG_MIROperationDOL, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
    {EMVTAG_MIRApplicationInfo, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 5, 5, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
    {EMVTAG_MIRTransProcessingMode, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRIssuerCertificateSN, EMVTAGUPDATECONDITION_K | EMVTAGUPDATECONDITION_RA, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRKernelVerificationResults, EMVTAGUPDATECONDITION_K , 2, 2, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_RUPAYDF7C,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA,0,255,EMVTAGFORMAT_AN,EMVTAGTYPE_RUPAY},
    {EMVTAG_PURETAID,EMVTAGUPDATECONDITION_K,0,16,EMVTAGFORMAT_B,EMVTAGTYPE_PURE},
	{EMVTAG_DSSummary2,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,8,16,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DSSummary3,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_RA|EMVTAGUPDATECONDITION_DET,8,16,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_BalanceBeforeGAC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
	{EMVTAG_BalanceAfterGAC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PayassDataNeeded,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_CDOL1RelatedData,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS | EMVTAGTYPE_JSPEEDY},
    {EMVTAG_DSACType,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DSInputTerm,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,8,8,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DSODSInfoReader,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DSSummaryStatus,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_KernelID,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DSVNTerm,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_POSTGACPDS,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PREGACPDS,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_ProfirstWF,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PDOLData,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TagsToRead,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_DRDOLRelatedData,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_ReferenceControlParameter,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_ErrorIndication,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_UserInterReqData,EMVTAGUPDATECONDITION_K,22,22,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_CARDINPUTCAP,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PAYPASSCVMRequired,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PAYPASSNOCVMRequired,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TermUDOL,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_KernelConfiguration,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_MaxLifeTimeTornLog,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_MaxNumTornLog,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_magcvmrequirer,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_SecurityCapability,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TACDefault,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TACDenial,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TACOnline,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_clessofflinelimitamt,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
    {EMVTAG_clessofflineamt,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
    {EMVTAG_ondevRTCL,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
    {EMVTAG_termcvm_limit,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TimeOutValue,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_IDSStatus,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_OutcomeParameterSet,EMVTAGUPDATECONDITION_K,8,8,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_Paypassconverttrack1,EMVTAGUPDATECONDITION_K,0,56,EMVTAGFORMAT_ANS,EMVTAGTYPE_PAYPASS},
    {EMVTAG_Paypassconverttrack2,EMVTAGUPDATECONDITION_K,0,8,EMVTAGFORMAT_CN,EMVTAGTYPE_PAYPASS},
    {EMVTAG_magnocvmrequirer,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_MessageHoldTime,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_N,EMVTAGTYPE_PAYPASS},
    {EMVTAG_HoldTimeValue,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_PhoneMessageTable,EMVTAGUPDATECONDITION_K,0,8,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_MinimumRelayResistanceGracePeriod,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_MaximumRelayResistanceGracePeriod,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_TerminalExpectedTTFRRCAPDU,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_TerminalExpectedTTFRRPAPDU,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_RelayResistanceAccuracyThreshold,EMVTAGUPDATECONDITION_K,0,2,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_RRTTimeMismatchThreshold,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_TerminalRelayResistanceEntropy,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,255,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_DeviceRelayResistanceEntropy,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,4,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_MinTimeForProcessingRelayResistanceAPDU,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,2,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_MaxTimeForProcessingRelayResistanceAPDU,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,2,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_DeviceEstimatedTransTForRRRAPDU,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,2,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_MeasureRelayResistanceProcessingTime,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,2,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_RRPCounter,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,1,1,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_MIRTACDenial, EMVTAGUPDATECONDITION_K, 5, 5, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRTACOnline, EMVTAGUPDATECONDITION_K, 5, 5, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRTACDefault, EMVTAGUPDATECONDITION_K, 5, 5, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
	{EMVTAG_MIRDataExchangeTagLis, EMVTAGUPDATECONDITION_K, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
    {EMVTAG_TornRecord,EMVTAGUPDATECONDITION_K,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_WriteBeforeGAC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_WriteAfterGAC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_ACT|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_PaypassDataToSend,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_PaypassDataRecord,EMVTAGUPDATECONDITION_K,0,65535,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
	{EMVTAG_DiscretionaryData,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_PAYPASS},
    {EMVTAG_TermDDOL,EMVTAGUPDATECONDITION_K,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_TermTDOL,EMVTAGUPDATECONDITION_K,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
    {EMVTAG_Threshold,EMVTAGUPDATECONDITION_K,4,4,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
    {EMVTAG_MaxTargetPercent,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_TargetPercent,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_bShowRandNum,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_bForceOnline,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_RupayCardKpsk, EMVTAGUPDATECONDITION_K, 16, 16, EMVTAGFORMAT_N, EMVTAGTYPE_RUPAY},
    {EMVTAG_RupayServiceQualifier, EMVTAGUPDATECONDITION_K, 5, 5, EMVTAGFORMAT_N, EMVTAGTYPE_RUPAY},
    {EMVTAG_TagsToReadYet,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_TagsToWriteYetAfterGenAC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_TagsToWriteYetBeforeGenAC,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_TagsMissingPDOLDataFlag,EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET,0,65535,EMVTAGFORMAT_B, EMVTAGTYPE_PAYPASS},
	{EMVTAG_BancomatCCVR,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
	{EMVTAG_BancomatTACSwitchInterface,EMVTAGUPDATECONDITION_K,5,5,EMVTAGFORMAT_B,EMVTAGTYPE_BANCOMAT|EMVTAGTYPE_PURE},
	{EMVTAG_SCRIPT71RESULT,EMVTAGUPDATECONDITION_K,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_SCRIPT72RESULT,EMVTAGUPDATECONDITION_K,0,128,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_CDOL2RelatedData,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_SupportTermCheck,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_DDOLRelatedData,EMVTAGUPDATECONDITION_K,0,255,EMVTAGFORMAT_B,EMVTAGTYPE_ALL},
    {EMVTAG_ICCPIN_EPKModul,EMVTAGUPDATECONDITION_K,0,248,EMVTAGFORMAT_B,EMVTAGTYPE_EMV|EMVTAGTYPE_NSICCS},
	{EMVTAG_JCBCombinationOptions,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_JSPEEDY},
	{EMVTAG_TermTypeModified,EMVTAGUPDATECONDITION_K,1,1,EMVTAGFORMAT_N,EMVTAGTYPE_EXPRESSPAY},
    {EMVTAG_MIRODOLData, EMVTAGUPDATECONDITION_K, 0, 255, EMVTAGFORMAT_B, EMVTAGTYPE_MIR},
    {EMVTAG_JCBRemovalTimeout,EMVTAGUPDATECONDITION_K,2,2,EMVTAGFORMAT_N,EMVTAGTYPE_JSPEEDY|EMVTAGTYPE_PURE},
	{EMVTAG_JCBStaticTIP,EMVTAGUPDATECONDITION_K,3,3,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
	{EMVTAG_JCBThresholdRandomSelect,EMVTAGUPDATECONDITION_K,6,6,EMVTAGFORMAT_N,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_ONLINEENCPIN,EMVTAGUPDATECONDITION_K,0,256,EMVTAGFORMAT_B,EMVTAGTYPE_JSPEEDY},
    {EMVTAG_PUREStatusCheckSupportFlag, EMVTAGUPDATECONDITION_K, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_PURE|EMVTAGTYPE_PAYWAVE},
    {EMVTAG_PUREZeroAmountAllowedFlag, EMVTAGUPDATECONDITION_K, 1, 1, EMVTAGFORMAT_B, EMVTAGTYPE_PURE|EMVTAGTYPE_PAYWAVE},
    {EMVTAG_PUREKernelCap, EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET, 5, 5, EMVTAGFORMAT_B, EMVTAGTYPE_PURE},
    {EMVTAG_PUREMTOL, EMVTAGUPDATECONDITION_K|EMVTAGUPDATECONDITION_DET, 50, 255, EMVTAGFORMAT_B, EMVTAGTYPE_PURE},
	{"\x00\x00\x00",0}
};


int emvbase_tagtotalnumread(void)
{
	int i = 0;

	while(1)
	{
		if(gEMVBaseTagBaseLib[i].Tag[0] == 0)
		{
			return i;
		}
		i++;
	}
}

static int	emvbase_compare_tagitems(const unsigned char *pa, const unsigned char *pb)
{
	return memcmp(pa,pb,3);

}

int emvbase_TagBaseLib_read(unsigned char *tag,unsigned char taglen,EMVBASETAGCVLITEM *emvtagitem,unsigned int apptype)
{
	int cmpresult,minnum,maxnum,cmpnum;
	unsigned char tmptag[3];
    unsigned char readresult = 0;

	if(gEMVBaseTagBaseLibnum == 0)
	{
		gEMVBaseTagBaseLibnum = emvbase_tagtotalnumread();
	}

	readresult = 1;

    if(gEMVBaseTagBaseLibnum != 0)
	{
	    memset(tmptag,0,sizeof(tmptag));
		memcpy(tmptag,tag,(taglen>3)?3:(taglen));
		minnum = 0;
		maxnum = gEMVBaseTagBaseLibnum-1;

		cmpresult = 0;

		while(1)
		{
		    if((maxnum-minnum) == 1)
		    {
				cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[minnum].Tag);
				if(cmpresult)
				{
					cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[maxnum].Tag);
					if(cmpresult)
					{
						break;
					}
					cmpnum = maxnum;
				}
				else
				{
					cmpnum = minnum;
				}
		    }
			else
			{
		   		cmpnum = ((maxnum-minnum)>>1)+minnum;
			}

			cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[cmpnum].Tag);

			if(cmpresult < 0)
			{
			    if(maxnum == 0)
			    {
			    	break;
			    }
				maxnum = cmpnum;
			}
			else if(cmpresult > 0)
			{
			    if(minnum >= gEMVBaseTagBaseLibnum-1)
			    {
					break;
			    }
				minnum = cmpnum;
			}
            else
            {
                if(gEMVBaseTagBaseLib[cmpnum].SupAppType & apptype)
                {
                    readresult = 0;
                	break;
                }


                minnum = cmpnum;
            	while(minnum>0)
            	{
            		cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[minnum-1].Tag);
					if(cmpresult)
					{
						break;
					}
					minnum--;
					if(gEMVBaseTagBaseLib[minnum].SupAppType & apptype)
	                {
	                    cmpnum = minnum;
	                    readresult = 0;
	                	break;
	                }
            	}


			   maxnum = cmpnum;
			   while(maxnum<gEMVBaseTagBaseLibnum)
			   {
				   cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[maxnum+1].Tag);
				   if(cmpresult)
				   {
					   break;
				   }
				   maxnum++;
				   if(gEMVBaseTagBaseLib[maxnum].SupAppType & apptype)
	               {
	                    cmpnum = maxnum;
	                    readresult = 0;
	                	break;
	               }
			   }

			   break;

            }


		}
    }


	if(emvtagitem != NULL)
	{
	    if(readresult)
	    {
			memset(emvtagitem,0,sizeof(EMVBASETAGCVLITEM));
	    }
		else
		{
		    memset(emvtagitem,0,sizeof(EMVBASETAGCVLITEM));
			memcpy(emvtagitem->Tag,(unsigned char *)&gEMVBaseTagBaseLib[cmpnum].Tag[0],3);
			emvtagitem->updatecondition = gEMVBaseTagBaseLib[cmpnum].updatecondition;
            emvtagitem->minlen = gEMVBaseTagBaseLib[cmpnum].minlen;
            emvtagitem->maxlen = gEMVBaseTagBaseLib[cmpnum].maxlen;
			emvtagitem->datafomat = gEMVBaseTagBaseLib[cmpnum].datafomat;
			emvtagitem->SupAppType = gEMVBaseTagBaseLib[cmpnum].SupAppType;
		}
	}

	return readresult;
}

int emvbase_TagBaseLib_read_condition(unsigned char *tag,unsigned char taglen,unsigned int apptype,unsigned char mode,unsigned char updatecondition,EMVBASETAGCVLITEM *emvtagitem)
{
	int cmpresult,minnum,maxnum,cmpnum;
	unsigned char tmptag[3];
    unsigned char readresult = 0;

	if(gEMVBaseTagBaseLibnum == 0)
	{
		gEMVBaseTagBaseLibnum = emvbase_tagtotalnumread();
	}

	readresult = 1;

    if(gEMVBaseTagBaseLibnum != 0)
	{
	    memset(tmptag,0,sizeof(tmptag));
		memcpy(tmptag,tag,(taglen>3)?3:(taglen));
		minnum = 0;
		maxnum = gEMVBaseTagBaseLibnum-1;

		cmpresult = 0;

		while(1)
		{
		    if((maxnum-minnum) == 1)
		    {
				cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[minnum].Tag);
				if(cmpresult)
				{
					cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[maxnum].Tag);
					if(cmpresult)
					{
						break;
					}
					cmpnum = maxnum;
				}
				else
				{
					cmpnum = minnum;
				}
		    }
			else
			{
		   		cmpnum = ((maxnum-minnum)>>1)+minnum;
			}

			cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[cmpnum].Tag);

			if(cmpresult < 0)
			{
			    if(maxnum == 0)
			    {
			    	break;
			    }
				maxnum = cmpnum;
			}
			else if(cmpresult > 0)
			{
			    if(minnum >= gEMVBaseTagBaseLibnum-1)
			    {
					break;
			    }
				minnum = cmpnum;
			}
            else
            {
                if(gEMVBaseTagBaseLib[cmpnum].SupAppType & apptype)
                {
					 #if 0 /*Modify by luohuidong at 2017.04.08  13:53 */
                        readresult = 0;
                    	break;
                    #else
                        if(1 == mode)
                        {
                            if(gEMVBaseTagBaseLib[cmpnum].updatecondition & updatecondition)//luohuidong 2017.04.08 14:10
                            {
                               readresult = 0;
                            }
                            break;
                        }
                        else
                        {
                            readresult = 0;
                    	    break;
                        }
                    #endif /* if 0 */
                }


                minnum = cmpnum;
            	while(minnum>0)
            	{
            		cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[minnum-1].Tag);
					if(cmpresult)
					{
						break;
					}
					minnum--;
					if(gEMVBaseTagBaseLib[minnum].SupAppType & apptype)
	                {
						#if 0 /*Modify by luohuidong at 2017.04.08  14:1 */
    	                    cmpnum = minnum;
		                    readresult = 0;
		                	break;
                        #else
                            if(1 == mode)
                            {
                                if(gEMVBaseTagBaseLib[minnum].updatecondition & updatecondition)//luohuidong 2017.04.08 14:10
                                {
                                    cmpnum = minnum;
            	                    readresult = 0;
                                }
                                break;
                            }
                            else
                            {
                                cmpnum = minnum;
        	                    readresult = 0;
        	                	break;
                            }
                        #endif /* if 0 */
	                }
            	}


			   maxnum = cmpnum;
			   while(maxnum<gEMVBaseTagBaseLibnum)
			   {
				   cmpresult = emvbase_compare_tagitems(tmptag,gEMVBaseTagBaseLib[maxnum+1].Tag);
				   if(cmpresult)
				   {
					   break;
				   }
				   maxnum++;
				   if(gEMVBaseTagBaseLib[maxnum].SupAppType & apptype)
	               {
						#if 0 /*Modify by luohuidong at 2017.04.08  13:41 */
    	                    cmpnum = maxnum;
		                    readresult = 0;
		                	break;
                        #else
                            cmpnum = maxnum;
                            if(1 == mode)
                            {
                                if(gEMVBaseTagBaseLib[maxnum].updatecondition & updatecondition)//luohuidong 2017.04.08 14:10
                                {
        	                        readresult = 0;
                                }
                                 break;
                            }
                            else
                            {
        	                    readresult = 0;
                                break;
                            }
                        #endif /* if 0 */
	               }
			   }

			   break;

            }


		}
    }


	if(emvtagitem != NULL)
	{
	    if(readresult)
	    {
			memset(emvtagitem,0,sizeof(EMVBASETAGCVLITEM));
	    }
		else
		{
		    memset(emvtagitem,0,sizeof(EMVBASETAGCVLITEM));
			memcpy(emvtagitem->Tag,(unsigned char *)&gEMVBaseTagBaseLib[cmpnum].Tag[0],3);
			emvtagitem->updatecondition = gEMVBaseTagBaseLib[cmpnum].updatecondition;
            emvtagitem->minlen = gEMVBaseTagBaseLib[cmpnum].minlen;
            emvtagitem->maxlen = gEMVBaseTagBaseLib[cmpnum].maxlen;
			emvtagitem->datafomat = gEMVBaseTagBaseLib[cmpnum].datafomat;
			emvtagitem->SupAppType = gEMVBaseTagBaseLib[cmpnum].SupAppType;
		}
	}

	return readresult;
}


unsigned char emvbase_checktableisok()			//for self-debug
{
	int num = emvbase_tagtotalnumread();
	int i;
	signed char rlt;
	unsigned int type = 0;
	for(i = 0 ; i < num ; i++)
	{
		EMVBase_Trace("tag:%02X%02X%02X",gEMVBaseTagBaseLib[i].Tag[0],gEMVBaseTagBaseLib[i].Tag[1],gEMVBaseTagBaseLib[i].Tag[2]);
		if(!memcmp("\x00\x00\x00",gEMVBaseTagBaseLib[i+1].Tag,3))
		{
			EMVBase_Trace(" finsh\r\n");
			break;
		}

		rlt = memcmp(gEMVBaseTagBaseLib[i].Tag,gEMVBaseTagBaseLib[i+1].Tag,3);
		EMVBase_Trace(" rlt = %d\r\n",rlt);
		if(rlt == 0)
		{
			type |= gEMVBaseTagBaseLib[i].SupAppType;
			if(type & gEMVBaseTagBaseLib[i+1].SupAppType)
			{
				EMVBase_Trace("\r\nerror!\r\n");

				while(1)
				{

				}
			}
		}
		else if(rlt > 0)
		{
			EMVBase_Trace("\r\nerror!\r\n");
			while(1)
			{

			}
		}
		else
		{
			type = 0;
		}
	}
}

