#ifndef SDKPUREPRIVATE_H
#define SDKPUREPRIVATE_H

#define SDK_PURE_STATUS_PPSE 					0x00
#define SDK_PURE_STATUS_SELECTAID 				0x01
#define SDK_PURE_STATUS_GPO		 				0x02
#define SDK_PURE_STATUS_READRECORD				0x03
#define SDK_PURE_STATUS_TRM						0x04
#define SDK_PURE_STATUS_PROCESSREST				0x05
#define SDK_PURE_STATUS_TAA						0x06
#define SDK_PURE_STATUS_ODA						0x07
#define SDK_PURE_STATUS_CVM						0x08
#define SDK_PURE_STATUS_ISSUERUPDATE			0x09
#define SDK_PURE_STATUS_RESELECTAID				0x0A
#define SDK_PURE_STATUS_PUTDATA_AFTERGPO		0x0B
#define SDK_PURE_STATUS_GETDATA					0x0C
#define SDK_PURE_STATUS_TRANSINIT				0x0D
#define SDK_PURE_STATUS_DIFFEREMVBASE			0x0F
#define SDK_PURE_STATUS_CAMSELECT				0x11
#define SDK_PURE_STATUS_READBALANCE_AFTERGAC	0x12
#define SDK_PURE_STATUS_PUTDATA_AFTERGAC        0x13
#define SDK_PURE_STATUS_KERNEL_DEACTIVATE       0x14

extern int sdkPureSetSendOutcome(void (*fun_pointer)());
extern int sdkPureSetSendUIRequest(void (*fun_pointer)(int type));

#endif
